import * as XLSX from 'xlsx';
import { REPORT_SOURCES, type ReportSnapshot } from './reportSources';
import { reportColumns, type ReportSection, type ReportValue } from './reportModel';

export type WorkbookContext = { from: string; to: string; branches: string[]; generatedBy: string; loadedAt: string; snapshot: ReportSnapshot };
const moneyColumn = (key: string) => /\(INR\)|amount|price|cost|subtotal|total|paid|balance|refund|discount|expected cash|closing cash|opening cash/i.test(key)
  && !/count|qty|quantity|percent|rate|\bID\b|at$|date|type|method|status/i.test(key);
const numericColumn = (key: string) => moneyColumn(key) || /(?:^|\s)(quantity|qty|tax|cost|price|rate|count|cash|upi|card|credit|wallet)(?:$|\s)/i.test(key);

function excelValue(key: string, value: ReportValue) {
  if (typeof value === 'string' && numericColumn(key) && /^-?\d+(\.\d+)?$/.test(value)) return Number(value);
  // Identifiers, customer text and strings beginning with '=' stay text.
  return value;
}
function sheetName(title: string, used: Set<string>) {
  const base = title.replace(/[\[\]:*?/\\]/g, ' ').replace(/\s+/g, ' ').slice(0, 27).trim() || 'Details';
  let name = base, suffix = 1;
  while (used.has(name.toLowerCase())) name = `${base.slice(0, 26)} ${++suffix}`;
  used.add(name.toLowerCase()); return name;
}

export function buildReportWorkbook(sections: ReportSection[], context: WorkbookContext) {
  const workbook = XLSX.utils.book_new();
  workbook.Props = { Title: 'VRSNB and Cafe Branch Reports', Author: context.generatedBy, Subject: `${context.from} to ${context.to}` };
  const used = new Set<string>(['contents']);
  const contents = [['VRSNB ADMIN — BRANCH REPORTS'],
    [`Branches: ${context.branches.join(' + ')} | Period: ${context.from} to ${context.to} | Time zone: Asia/Kolkata | Currency: INR`],
    [`Refreshed: ${context.loadedAt || 'Not completed'} | Generated by: ${context.generatedBy}`],
    ['Status', Object.values(context.snapshot).some(source => source.status !== 'ready') ? 'INCOMPLETE — see source status below' : 'All requested sources loaded'],
    ['Worksheet', 'Section', 'Records', 'Scope / explanation']];
  const indexSheet = XLSX.utils.aoa_to_sheet(contents);
  XLSX.utils.book_append_sheet(workbook, indexSheet, 'Contents');
  let indexRow = 5;
  for (const section of sections) {
    const columns = reportColumns(section.rows);
    const headers = columns.length ? columns : ['Status'];
    // Stay below worksheet row limits, with deterministic names and a contents
    // entry for every part. Never silently shorten a large report.
    const chunks = Math.max(1, Math.ceil(section.rows.length / 100000));
    for (let part = 0; part < chunks; part++) {
      const rows = section.rows.slice(part * 100000, (part + 1) * 100000);
      const name = sheetName(`${section.title}${chunks > 1 ? ` ${part + 1}` : ''}`, used);
      const status = context.snapshot[section.sourceId];
      const statusText = status?.status === 'error' ? `INCOMPLETE: ${status.error}` : 'Loaded';
      const body = rows.length ? rows.map(row => headers.map(key => excelValue(key, row[key] ?? null))) : [[status?.status === 'error' ? 'Could not load this section. See Contents.' : 'No records for this scope.']];
      const sheet = XLSX.utils.aoa_to_sheet([
        [section.title],
        [`${context.branches.join(' + ')} | ${context.from} to ${context.to} | INR | Times shown in original recorded ISO format`],
        [section.description],
        [`${rows.length} rows${chunks > 1 ? `, part ${part + 1} of ${chunks}` : ''}. ${statusText}`],
        headers,
        ...body,
      ]);
      sheet['!merges'] = [0, 1, 2, 3].map(r => ({ s: { r, c: 0 }, e: { r, c: Math.max(1, headers.length - 1) } }));
      sheet['!rows'] = [{ hpt: 26 }, { hpt: 24 }, { hpt: 42 }, { hpt: 24 }, { hpt: 30 }];
      sheet['!cols'] = headers.map(key => ({ wch: Math.min(52, Math.max(16, key.length + 2, ...rows.slice(0, 300).map(row => Math.min(52, String(row[key] ?? '').length + 1)))) }));
      sheet['!autofilter'] = { ref: XLSX.utils.encode_range({ s: { r: 4, c: 0 }, e: { r: Math.max(4, rows.length + 4), c: headers.length - 1 } }) };
      rows.forEach((row, r) => headers.forEach((key, c) => {
        const cell = sheet[XLSX.utils.encode_cell({ r: r + 5, c })];
        if (cell?.t === 'n') cell.z = moneyColumn(key) ? '#,##0.00;[Red](#,##0.00);0.00' : '#,##0.###;[Red](#,##0.###);0';
      }));
      XLSX.utils.book_append_sheet(workbook, sheet, name);
      XLSX.utils.sheet_add_aoa(indexSheet, [[name, section.title, rows.length, section.description]], { origin: indexRow });
      indexSheet[`A${indexRow + 1}`].l = { Target: `#'${name.replace(/'/g, "''")}'!A1` };
      indexRow++;
    }
  }
  const sources = REPORT_SOURCES.map(source => [source.title, context.snapshot[source.id]?.status || 'Not loaded', context.snapshot[source.id]?.rows.length || 0,
    context.snapshot[source.id]?.error || (source.scope === 'current' ? 'Current register across all dates' : 'Selected reporting period')]);
  XLSX.utils.sheet_add_aoa(indexSheet, [[], ['SOURCE COVERAGE'], ['Source', 'Status', 'Source rows', 'Scope / load error'], ...sources,

    ['Reading the workbook', 'Source registers can describe the same transaction. Use Branch comparison for sales totals; do not add every worksheet together.'],
    ['Nested details', 'Item lists, payment breakdowns and other nested records are expanded. Parent ID links each detail to its source record.'],
    ['Dates', 'ISO timestamps retain their recorded offset or Z (UTC). Daily sales use India business dates. Current registers are not historical balances.'],
  ], { origin: indexRow });
  indexSheet['!cols'] = [{ wch: 34 }, { wch: 44 }, { wch: 16 }, { wch: 95 }];
  indexSheet['!merges'] = [0, 1, 2].map(r => ({ s: { r, c: 0 }, e: { r, c: 3 } }));
  return workbook;
}

export function downloadReportWorkbook(sections: ReportSection[], context: WorkbookContext) {
  XLSX.writeFile(buildReportWorkbook(sections, context), `VRSNB_Cafe_Reports_${context.from}_to_${context.to}.xlsx`, { compression: true });
}
