import type { MenuItem } from '@/types';

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  // === SOUTH INDIAN BREAKFAST (7AM - 11AM) ===
  { id: 'sib-1', name: 'Idly (2pc)', price: 39, category: 'south-indian-breakfast', timing: '7AM - 11AM', enabled: true },
  { id: 'sib-2', name: 'Plain Dosa', price: 55, category: 'south-indian-breakfast', timing: '7AM - 11AM', enabled: true },
  { id: 'sib-3', name: 'Set Dosa (2pc)', price: 69, category: 'south-indian-breakfast', timing: '7AM - 11AM', enabled: true },
  { id: 'sib-4', name: 'Mushroom Dosa', price: 89, category: 'south-indian-breakfast', timing: '7AM - 11AM', enabled: true },
  { id: 'sib-5', name: 'Podi Dosa', price: 80, category: 'south-indian-breakfast', timing: '7AM - 11AM', enabled: true },
  { id: 'sib-6', name: 'Ghee Dosa', price: 80, category: 'south-indian-breakfast', timing: '7AM - 11AM', enabled: true },
  { id: 'sib-7', name: 'Sambar Vada', price: 40, category: 'south-indian-breakfast', timing: '7AM - 11AM', enabled: true },
  { id: 'sib-8', name: 'Masala Dosa', price: 69, category: 'south-indian-breakfast', timing: '7AM - 11AM', enabled: true },
  { id: 'sib-9', name: 'Ghee Pongal', price: 89, category: 'south-indian-breakfast', timing: '7AM - 11AM', enabled: true },
  { id: 'sib-10', name: 'Vada (1pc)', price: 19, category: 'south-indian-breakfast', timing: '7AM - 11AM', enabled: true },
  { id: 'sib-11', name: 'Lemon Rice', price: 69, category: 'south-indian-breakfast', timing: '7AM - 11AM', enabled: true },
  { id: 'sib-12', name: 'Pulihora', price: 69, category: 'south-indian-breakfast', timing: '7AM - 11AM', enabled: true },
  { id: 'sib-13', name: 'Tomato Bath', price: 69, category: 'south-indian-breakfast', timing: '7AM - 11AM', enabled: true },
  { id: 'sib-14', name: 'Ghee Veg Upma', price: 79, category: 'south-indian-breakfast', timing: '7AM - 11AM', enabled: true },
  { id: 'sib-15', name: 'Kesaribath', price: 39, category: 'south-indian-breakfast', timing: '7AM - 11AM', enabled: true },
  { id: 'sib-16', name: 'Onion Uttapam', price: 59, category: 'south-indian-breakfast', timing: '7AM - 11AM', enabled: true },
  { id: 'sib-17', name: 'Ghee Onion Uttapam', price: 89, category: 'south-indian-breakfast', timing: '7AM - 11AM', enabled: true },
  { id: 'sib-18', name: 'Rice Bath', price: 69, category: 'south-indian-breakfast', timing: '7AM - 11AM', enabled: true },

  // === SOUP (12PM - 10PM) ===
  { id: 'sou-1', name: 'Tomato Soup', price: 59, category: 'soup', timing: '12PM - 10PM', enabled: true },
  { id: 'sou-2', name: 'Corn Soup', price: 59, category: 'soup', timing: '12PM - 10PM', enabled: true },
  { id: 'sou-3', name: 'Hot n Sour Soup', price: 59, category: 'soup', timing: '12PM - 10PM', enabled: true },
  { id: 'sou-4', name: 'Lemon Coriander Soup', price: 59, category: 'soup', timing: '12PM - 10PM', enabled: true },
  { id: 'sou-5', name: 'Cream & Mushroom Soup', price: 79, category: 'soup', timing: '12PM - 10PM', enabled: true },
  { id: 'sou-6', name: 'Drum Stick Soup', price: 79, category: 'soup', timing: '12PM - 10PM', enabled: true },

  // === LUNCH (12PM - 3PM) ===
  { id: 'lun-1', name: 'Pappu Avakaya Rice', price: 89, category: 'lunch', timing: '12PM - 3PM', enabled: true },
  { id: 'lun-2', name: 'Gongura Rice', price: 89, category: 'lunch', timing: '12PM - 3PM', enabled: true },
  { id: 'lun-3', name: 'Rasam Rice', price: 79, category: 'lunch', timing: '12PM - 3PM', enabled: true },
  { id: 'lun-4', name: 'Curd Rice', price: 79, category: 'lunch', timing: '12PM - 3PM', enabled: true },
  { id: 'lun-5', name: 'Sambar Sadam', price: 89, category: 'lunch', timing: '12PM - 3PM', enabled: true },
  { id: 'lun-6', name: 'Bisibelebath', price: 89, category: 'lunch', timing: '12PM - 3PM', enabled: true },

  // === BIRIYANI (12PM - 3PM & 7PM - 10PM) ===
  { id: 'bir-1', name: 'Handi Biriyani', price: 169, category: 'biriyani', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'bir-2', name: 'Hyderabad Biriyani', price: 150, category: 'biriyani', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'bir-3', name: 'Tawa Biriyani', price: 140, category: 'biriyani', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'bir-4', name: 'Paneer Tikka Biriyani', price: 200, category: 'biriyani', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'bir-5', name: 'Jack Fruit Biriyani', price: 200, category: 'biriyani', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'bir-6', name: 'Veg Biriyani', price: 140, category: 'biriyani', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },

  // === MINI MEALS (12PM - 3PM) ===
  { id: 'mm-1', name: 'Mini Meals', price: 110, category: 'mini-meals', timing: '12PM - 3PM', enabled: true },

  // === TANDOORI STARTERS (12PM - 3PM & 7PM - 10PM) ===
  { id: 'tan-1', name: 'Paneer Tikka', price: 140, category: 'tandoori-starters', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'tan-2', name: 'Malai Paneer Tikka', price: 140, category: 'tandoori-starters', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'tan-3', name: 'Mushroom Tikka', price: 120, category: 'tandoori-starters', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'tan-4', name: 'Veg Sheek Kabab', price: 120, category: 'tandoori-starters', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'tan-5', name: 'Achari Kabab', price: 130, category: 'tandoori-starters', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'tan-6', name: 'Haryali Kabab', price: 130, category: 'tandoori-starters', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'tan-7', name: 'Soya Chop Kabab', price: 140, category: 'tandoori-starters', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'tan-8', name: 'Harabara Kabab', price: 120, category: 'tandoori-starters', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'tan-9', name: 'Stuffed Tandoori Aloo', price: 189, category: 'tandoori-starters', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'tan-10', name: 'Grilled Corn', price: 110, category: 'tandoori-starters', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'tan-11', name: 'Tandoori Platter', price: 190, category: 'tandoori-starters', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'tan-12', name: 'Pineapple Tandoori', price: 160, category: 'tandoori-starters', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'tan-13', name: 'Tandoori Momos', price: 110, category: 'tandoori-starters', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },

  // === CHINESE (12PM - 3PM & 7PM - 10PM) ===
  { id: 'chi-1', name: 'Veg Manchurian', price: 99, category: 'chinese', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'chi-2', name: 'Gobi Manchurian', price: 90, category: 'chinese', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'chi-3', name: 'Paneer Manchurian', price: 110, category: 'chinese', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'chi-4', name: 'Mushroom Manchurian', price: 99, category: 'chinese', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'chi-5', name: 'Baby Corn Manchurian', price: 99, category: 'chinese', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'chi-6', name: 'Chilli Paneer', price: 120, category: 'chinese', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'chi-7', name: 'Chilli Gobi', price: 110, category: 'chinese', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'chi-8', name: 'Chilli Mushroom', price: 110, category: 'chinese', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'chi-9', name: 'Paneer 65 Dry', price: 120, category: 'chinese', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'chi-10', name: 'Gobi 65 Dry', price: 90, category: 'chinese', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'chi-11', name: 'Baby Corn 65 Dry', price: 110, category: 'chinese', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'chi-12', name: 'Masala Pepper Corn', price: 110, category: 'chinese', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'chi-13', name: 'Crispy Mix Vegetables', price: 79, category: 'chinese', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'chi-14', name: 'Veg Ball Manchurian', price: 80, category: 'chinese', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },

  // === RICE VARIETIES (12PM - 10PM) ===
  { id: 'ric-1', name: 'Veg Fried Rice', price: 110, category: 'rice-varieties', timing: '12PM - 10PM', enabled: true },
  { id: 'ric-2', name: 'Paneer Fried Rice', price: 130, category: 'rice-varieties', timing: '12PM - 10PM', enabled: true },
  { id: 'ric-3', name: 'Gobi Fried Rice', price: 130, category: 'rice-varieties', timing: '12PM - 10PM', enabled: true },
  { id: 'ric-4', name: 'Mushroom Fried Rice', price: 130, category: 'rice-varieties', timing: '12PM - 10PM', enabled: true },
  { id: 'ric-5', name: 'Veg Schezwan Fried Rice', price: 130, category: 'rice-varieties', timing: '12PM - 10PM', enabled: true },
  { id: 'ric-6', name: 'Veg Schezwan Paneer Fried Rice', price: 130, category: 'rice-varieties', timing: '12PM - 10PM', enabled: true },
  { id: 'ric-7', name: 'Veg Schezwan Gobi Fried Rice', price: 130, category: 'rice-varieties', timing: '12PM - 10PM', enabled: true },
  { id: 'ric-8', name: 'Veg Noodles', price: 110, category: 'rice-varieties', timing: '12PM - 10PM', enabled: true },
  { id: 'ric-9', name: 'Paneer Noodles', price: 130, category: 'rice-varieties', timing: '12PM - 10PM', enabled: true },
  { id: 'ric-10', name: 'Mushroom Noodles', price: 130, category: 'rice-varieties', timing: '12PM - 10PM', enabled: true },
  { id: 'ric-11', name: 'Gobi Noodles', price: 130, category: 'rice-varieties', timing: '12PM - 10PM', enabled: true },
  { id: 'ric-12', name: 'SNB Special Triple Rice', price: 189, category: 'rice-varieties', timing: '12PM - 10PM', enabled: true },
  { id: 'ric-13', name: 'Jeera Rice', price: 110, category: 'rice-varieties', timing: '12PM - 10PM', enabled: true },
  { id: 'ric-14', name: 'Ghee Rice', price: 110, category: 'rice-varieties', timing: '12PM - 10PM', enabled: true },
  { id: 'ric-15', name: 'Green Peas Pulav', price: 130, category: 'rice-varieties', timing: '12PM - 10PM', enabled: true },
  { id: 'ric-16', name: 'Veg Pulav', price: 130, category: 'rice-varieties', timing: '12PM - 10PM', enabled: true },

  // === BREADS (12PM - 3PM & 7PM - 10PM) ===
  { id: 'bre-1', name: 'Plain Naan', price: 40, category: 'breads', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'bre-2', name: 'Butter Naan', price: 45, category: 'breads', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'bre-3', name: 'Garlic Naan', price: 45, category: 'breads', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'bre-4', name: 'Roti', price: 30, category: 'breads', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'bre-5', name: 'Butter Roti', price: 35, category: 'breads', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'bre-6', name: 'Stuffed Paratha', price: 45, category: 'breads', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'bre-7', name: 'Stuffed Onion Paratha', price: 50, category: 'breads', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'bre-8', name: 'Stuffed Paneer Paratha', price: 65, category: 'breads', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'bre-9', name: 'Kashmiri Naan', price: 60, category: 'breads', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'bre-10', name: 'Plain Kulcha', price: 45, category: 'breads', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'bre-11', name: 'Stuffed Kulcha', price: 70, category: 'breads', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },
  { id: 'bre-12', name: 'Aloo Paratha', price: 90, category: 'breads', timing: '12PM - 3PM & 7PM - 10PM', enabled: true },

  // === PAROTTA (7PM - 10PM) ===
  { id: 'par-1', name: 'Kottu Parotta + Kurma', price: 79, category: 'parotta', timing: '7PM - 10PM', enabled: true },
  { id: 'par-2', name: 'Fried Parotta + Kurma', price: 70, category: 'parotta', timing: '7PM - 10PM', enabled: true },
  { id: 'par-3', name: 'Potlam Parotta + Kurma', price: 130, category: 'parotta', timing: '7PM - 10PM', enabled: true },
  { id: 'par-4', name: 'Noolu Parotta + Kurma', price: 50, category: 'parotta', timing: '7PM - 10PM', enabled: true },
  { id: 'par-5', name: 'Parotta + Kurma', price: 40, category: 'parotta', timing: '7PM - 10PM', enabled: true },
  { id: 'par-6', name: 'Bun Parotta + Kurma', price: 60, category: 'parotta', timing: '7PM - 10PM', enabled: true },

  // === GRAVY & CURRY (7PM - 10PM) ===
  { id: 'gra-1', name: 'Paneer Tikka Masala', price: 170, category: 'gravy-curry', timing: '7PM - 10PM', enabled: true },
  { id: 'gra-2', name: 'Paneer Butter Masala', price: 160, category: 'gravy-curry', timing: '7PM - 10PM', enabled: true },
  { id: 'gra-3', name: 'Palak Paneer', price: 160, category: 'gravy-curry', timing: '7PM - 10PM', enabled: true },
  { id: 'gra-4', name: 'Mix Veg Kadai', price: 160, category: 'gravy-curry', timing: '7PM - 10PM', enabled: true },
  { id: 'gra-5', name: 'Mix Veg Kolhapuri', price: 170, category: 'gravy-curry', timing: '7PM - 10PM', enabled: true },
  { id: 'gra-6', name: 'Palak Dal', price: 140, category: 'gravy-curry', timing: '7PM - 10PM', enabled: true },
  { id: 'gra-7', name: 'Dal Tadka', price: 140, category: 'gravy-curry', timing: '7PM - 10PM', enabled: true },
  { id: 'gra-8', name: 'Mushroom Masala', price: 160, category: 'gravy-curry', timing: '7PM - 10PM', enabled: true },
  { id: 'gra-9', name: 'Veg Kurma', price: 160, category: 'gravy-curry', timing: '7PM - 10PM', enabled: true },
  { id: 'gra-10', name: 'Dal Makhani', price: 160, category: 'gravy-curry', timing: '7PM - 10PM', enabled: true },
  { id: 'gra-11', name: 'Kadai Paneer', price: 160, category: 'gravy-curry', timing: '7PM - 10PM', enabled: true },
  { id: 'gra-12', name: 'Kadai Mushroom Masala', price: 160, category: 'gravy-curry', timing: '7PM - 10PM', enabled: true },
  { id: 'gra-13', name: 'Aloo Matar Subzi', price: 160, category: 'gravy-curry', timing: '7PM - 10PM', enabled: true },

  // === KIDS MENU (11AM - 10PM) ===
  { id: 'kid-1', name: 'Veg Burger', price: 70, category: 'kids-menu', timing: '11AM - 10PM', enabled: true },
  { id: 'kid-2', name: 'Veg Cheese Grilled Burger', price: 80, category: 'kids-menu', timing: '11AM - 10PM', enabled: true },
  { id: 'kid-3', name: 'Sandwich', price: 70, category: 'kids-menu', timing: '11AM - 10PM', enabled: true },
  { id: 'kid-4', name: 'Bombay Triple Sandwich', price: 99, category: 'kids-menu', timing: '11AM - 10PM', enabled: true },
  { id: 'kid-5', name: 'Cheese Grilled Sandwich', price: 99, category: 'kids-menu', timing: '11AM - 10PM', enabled: true },
  { id: 'kid-6', name: 'French Fries', price: 70, category: 'kids-menu', timing: '11AM - 10PM', enabled: true },
  { id: 'kid-7', name: 'Honey Chilli Potato', price: 99, category: 'kids-menu', timing: '11AM - 10PM', enabled: true },
  { id: 'kid-8', name: 'Corn Cheese Ball', price: 99, category: 'kids-menu', timing: '11AM - 10PM', enabled: true },
  { id: 'kid-9', name: 'Pizza', price: 99, category: 'kids-menu', timing: '11AM - 10PM', enabled: true },
  { id: 'kid-10', name: 'Veg Corn Pizza', price: 120, category: 'kids-menu', timing: '11AM - 10PM', enabled: true },
  { id: 'kid-11', name: 'Veg Cheese Pizza', price: 120, category: 'kids-menu', timing: '11AM - 10PM', enabled: true },
  { id: 'kid-12', name: 'Veg Paneer Tikka Pizza', price: 139, category: 'kids-menu', timing: '11AM - 10PM', enabled: true },
  { id: 'kid-13', name: 'Veg Farmhouse Pizza', price: 139, category: 'kids-menu', timing: '11AM - 10PM', enabled: true },
  { id: 'kid-14', name: 'Veg Momos', price: 99, category: 'kids-menu', timing: '11AM - 10PM', enabled: true },

  // === BEVERAGES (6AM - 10PM) ===
  { id: 'bev-1', name: 'Tea', price: 20, category: 'beverages', timing: '6AM - 10PM', enabled: true },
  { id: 'bev-2', name: 'Coffee', price: 30, category: 'beverages', timing: '6AM - 10PM', enabled: true },
  { id: 'bev-3', name: 'Badam Milk Hot & Cold', price: 30, category: 'beverages', timing: '6AM - 10PM', enabled: true },
  { id: 'bev-4', name: 'Ice Tea', price: 40, category: 'beverages', timing: '6AM - 10PM', enabled: true },
  { id: 'bev-5', name: 'Lemon Tea', price: 20, category: 'beverages', timing: '6AM - 10PM', enabled: true },
  { id: 'bev-6', name: 'Tandoori Tea', price: 25, category: 'beverages', timing: '6AM - 10PM', enabled: true },
  { id: 'bev-7', name: 'Black Tea', price: 20, category: 'beverages', timing: '6AM - 10PM', enabled: true },
  { id: 'bev-8', name: 'Honey Extra', price: 5, category: 'beverages', timing: '6AM - 10PM', enabled: true },
  { id: 'bev-9', name: 'Lassi Plain', price: 60, category: 'beverages', timing: '6AM - 10PM', enabled: true },
  { id: 'bev-10', name: 'Mango Lassi', price: 70, category: 'beverages', timing: '6AM - 10PM', enabled: true },
  { id: 'bev-11', name: 'Gulab Shake', price: 70, category: 'beverages', timing: '6AM - 10PM', enabled: true },
  { id: 'bev-12', name: 'Masala Shikanji', price: 50, category: 'beverages', timing: '6AM - 10PM', enabled: true },
  { id: 'bev-13', name: 'Badam Milk', price: 70, category: 'beverages', timing: '6AM - 10PM', enabled: true },
  { id: 'bev-14', name: 'Rose Milk', price: 60, category: 'beverages', timing: '6AM - 10PM', enabled: true },
  { id: 'bev-15', name: 'Butter Milk', price: 60, category: 'beverages', timing: '6AM - 10PM', enabled: true },

  // === EVENING SNACKS (3PM - 7PM) ===
  { id: 'snk-1', name: 'Mirchi Bajji (2pc)', price: 45, category: 'evening-snacks', timing: '3PM - 7PM', enabled: true },
  { id: 'snk-2', name: 'Banana Bajji (2pc)', price: 45, category: 'evening-snacks', timing: '3PM - 7PM', enabled: true },
  { id: 'snk-3', name: 'Onion Bonda', price: 45, category: 'evening-snacks', timing: '3PM - 7PM', enabled: true },
  { id: 'snk-4', name: 'Masala Mirchi Bajji', price: 49, category: 'evening-snacks', timing: '3PM - 7PM', enabled: true },
  { id: 'snk-5', name: 'Aloo Bonda', price: 40, category: 'evening-snacks', timing: '3PM - 7PM', enabled: true },
  { id: 'snk-6', name: 'Mix Bajji', price: 60, category: 'evening-snacks', timing: '3PM - 7PM', enabled: true },

  // === CHATS (3PM - 10PM) ===
  { id: 'cha-1', name: 'Pani Puri', price: 40, category: 'chats', timing: '3PM - 10PM', enabled: true },
  { id: 'cha-2', name: 'Masala Puri', price: 40, category: 'chats', timing: '3PM - 10PM', enabled: true },
  { id: 'cha-3', name: 'Dahi Puri', price: 50, category: 'chats', timing: '3PM - 10PM', enabled: true },
  { id: 'cha-4', name: 'Pav Bhaji', price: 70, category: 'chats', timing: '3PM - 10PM', enabled: true },
  { id: 'cha-5', name: 'Chole Bhature', price: 80, category: 'chats', timing: '3PM - 10PM', enabled: true },
  { id: 'cha-6', name: 'Vada Pav (2pc)', price: 50, category: 'chats', timing: '3PM - 10PM', enabled: true },
  { id: 'cha-7', name: 'Dabeli', price: 50, category: 'chats', timing: '3PM - 10PM', enabled: true },
  { id: 'cha-8', name: 'Raj Kachori', price: 60, category: 'chats', timing: '3PM - 10PM', enabled: true },
  { id: 'cha-9', name: 'Papdi Chat', price: 50, category: 'chats', timing: '3PM - 10PM', enabled: true },
  { id: 'cha-10', name: 'Bhel Puri', price: 50, category: 'chats', timing: '3PM - 10PM', enabled: true },
  { id: 'cha-11', name: 'Congress Masala', price: 50, category: 'chats', timing: '3PM - 10PM', enabled: true },
];
