import { useEffect, useMemo, useState } from 'react';
import { ArrowDownToLine, CheckCircle2, Package, Printer, Search, Trash2 } from 'lucide-react';
import { useAuthStore } from '@/stores/authStore';

type SourceBranch = 'SNB' | 'VRSNB';
type TransferIn = { id:string; source:SourceBranch; reference:string; itemName:string; expected:number; received:number; unit:'kg'|'pcs'; receivedAt:string; receivedBy:string; remarks:string; };
const KEY='packing-transfer-in-v1';
const read=():TransferIn[]=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};

export default function PackingTransferInTab(){
 const {currentUser}=useAuthStore(); const [rows,setRows]=useState<TransferIn[]>(read); const [q,setQ]=useState('');
 const [form,setForm]=useState({source:'SNB' as SourceBranch,reference:'',itemName:'',expected:'',received:'',unit:'kg' as 'kg'|'pcs',remarks:''});
 useEffect(()=>localStorage.setItem(KEY,JSON.stringify(rows)),[rows]);
 const filtered=useMemo(()=>rows.filter(r=>`${r.source} ${r.reference} ${r.itemName} ${r.remarks}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);
 const add=()=>{const expected=Number(form.expected),received=Number(form.received); if(!form.itemName.trim()||received<=0)return; setRows(v=>[{id:crypto.randomUUID(),...form,expected,received,receivedAt:new Date().toISOString(),receivedBy:currentUser?.displayName||currentUser?.username||'Packing Staff'},...v]); setForm(v=>({...v,reference:'',itemName:'',expected:'',received:'',remarks:''}));};
 const print=()=>{const w=window.open('','_blank');if(!w)return;w.document.write(`<html><head><style>body{font-family:Arial;padding:20px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #222;padding:7px;font-size:11px}</style></head><body><h2>PACKING TRANSFER-IN REGISTER</h2><table><tr><th>Date</th><th>From</th><th>Reference</th><th>Item</th><th>Expected</th><th>Received</th><th>Variance</th><th>Received By</th></tr>${filtered.map(r=>`<tr><td>${new Date(r.receivedAt).toLocaleString('en-IN')}</td><td>${r.source}</td><td>${r.reference||'-'}</td><td>${r.itemName}</td><td>${r.expected} ${r.unit}</td><td>${r.received} ${r.unit}</td><td>${(r.received-r.expected).toFixed(3)}</td><td>${r.receivedBy}</td></tr>`).join('')}</table></body></html>`);w.document.close();setTimeout(()=>w.print(),200)};
 return <div className="dashboard-screen min-h-screen p-4 md:p-6 space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">Packing stock control</p><h1 className="text-2xl font-black">Transfer In</h1><p className="text-xs text-muted-foreground">Track every item returned or transferred from SNB and VRSNB, including excess, shortage and leftover stock.</p></div><button onClick={print} className="h-10 px-4 rounded-xl border bg-card text-xs font-bold flex items-center gap-2"><Printer className="size-4"/>Print Register</button></div>
 <div className="grid gap-4 xl:grid-cols-[380px_1fr]"><section className="rounded-2xl border bg-card p-4 space-y-3"><h2 className="font-black flex items-center gap-2"><ArrowDownToLine className="size-4"/>Receive Stock</h2><div className="grid grid-cols-2 gap-2"><select value={form.source} onChange={e=>setForm({...form,source:e.target.value as SourceBranch})} className="h-10 rounded-xl border px-3"><option>SNB</option><option>VRSNB</option></select><input placeholder="Transfer reference" value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} className="h-10 rounded-xl border px-3"/></div><input placeholder="Item name *" value={form.itemName} onChange={e=>setForm({...form,itemName:e.target.value})} className="h-10 w-full rounded-xl border px-3"/><div className="grid grid-cols-3 gap-2"><input type="number" placeholder="Expected" value={form.expected} onChange={e=>setForm({...form,expected:e.target.value})} className="h-10 rounded-xl border px-2"/><input type="number" placeholder="Received *" value={form.received} onChange={e=>setForm({...form,received:e.target.value})} className="h-10 rounded-xl border px-2"/><select value={form.unit} onChange={e=>setForm({...form,unit:e.target.value as 'kg'|'pcs'})} className="h-10 rounded-xl border px-2"><option value="kg">KG</option><option value="pcs">Pcs</option></select></div><textarea placeholder="Remarks / reason for return or leftover" value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})} className="min-h-20 w-full rounded-xl border p-3"/><button onClick={add} className="h-11 w-full rounded-xl bg-emerald-600 text-white font-black flex items-center justify-center gap-2"><CheckCircle2 className="size-4"/>Confirm Transfer In</button></section>
 <section className="rounded-2xl border bg-card overflow-hidden"><div className="p-3 border-b flex items-center gap-2"><Search className="size-4 text-muted-foreground"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search item, branch or reference" className="h-9 flex-1 bg-transparent outline-none text-sm"/></div><div className="max-h-[68vh] overflow-auto"><table className="min-w-[850px] w-full text-xs"><thead className="sticky top-0 bg-slate-950 text-white"><tr>{['Date','From','Reference','Item','Expected','Received','Variance','Status',''].map(x=><th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody>{filtered.map(r=>{const variance=r.received-r.expected;return <tr key={r.id} className="border-t"><td className="p-3">{new Date(r.receivedAt).toLocaleString('en-IN')}</td><td className="p-3 font-black">{r.source}</td><td className="p-3">{r.reference||'-'}</td><td className="p-3 font-bold">{r.itemName}</td><td className="p-3">{r.expected} {r.unit}</td><td className="p-3">{r.received} {r.unit}</td><td className={`p-3 font-black ${variance<0?'text-red-600':variance>0?'text-amber-600':'text-emerald-600'}`}>{variance.toFixed(3)}</td><td className="p-3">{variance===0?'Matched':variance<0?'Shortage':'Excess / Leftover'}</td><td className="p-3"><button onClick={()=>setRows(v=>v.filter(x=>x.id!==r.id))}><Trash2 className="size-4 text-red-500"/></button></td></tr>})}{!filtered.length&&<tr><td colSpan={9} className="p-16 text-center text-muted-foreground"><Package className="size-8 mx-auto mb-2"/>No transfer-in records</td></tr>}</tbody></table></div></section></div></div>
}
